# Generated by Django 4.2 on 2023-11-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("html", models.TextField()),
                ("css", models.TextField()),
                ("preview_link", models.TextField(default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
