# Generated by Django 4.2 on 2023-11-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grapesjs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pages",
            name="is_home",
            field=models.BooleanField(default=False),
        ),
    ]
